config/routes.rb
Rails.application.routes.draw do
  # get 'hunter_profiles/new'
  root 'dashboards#index'

  resources :hunter_profiles do
    member do
      get 'offer'
      post 'offer'
    end
  end

  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations"
  }
  devise_scope :users do
    get 'sign_up', to: 'users/registrations#new'
    get 'sign_in', to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
  end

  # post 'offer', to: 'hunter_profiles#create_offer'

  resources :listings
  # resources :registrations
  # resources :sessions
  resources :hunter_profiles
  resources :employer_profiles

  # create new employments from the offer button
  resources :employments, only: [:new, :create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :employer_profile

  has_many :employments
  has_and_belongs_to_many :skills, :through => :listings_skills

  def get_required_skills
    # self.required_skills # some way of returning a set of skills
    self.skills
  end

  def offer(hunter)
    Employment.create(hunter, self)
  end

  def hunters
    # return all the listings from the employments table
    Employment.where(listing_id: self.id)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /listings
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  def show
    @listings = Listing.find(params[:id])
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  def create
    @listing = Listing.new(listing_params)
    @listing.employer_profile_id = current_user.id
    if @listing.save
      params[:listing][:skill].each do |skill|
        if skill[:skill_id].present?
          @listing.skills << Skill.find(skill[:skill_id].to_i)
        end
      end
      redirect_to @listing, notice: 'Listing was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /listings/1
  def update
    if @listing.update(listing_params)
      redirect_to @listing, notice: 'Listing was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /listings/1
  def destroy
    @listing.destroy
    redirect_to listings_url, notice: 'Listing was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def listing_params
      params[:listing].permit(:title, :body, :location, :accepted, :offered, :published,
        :min_salary, :max_salary, :hours)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
  
end

app/views/listings/_dashlisting.html.erb
<tbody>
  <tr>
    <td><%= @listing.hours %></td>
    <td><%= @listing.title %></td>
    <td><%= @listing.location %></td>
  </tr>
</tbody>

app/views/listings/_form.html.erb
<head>
<script>
$(document).ready(function(){
   if($('#listing_industry').val() == ""){
      $("#ski").attr('hidden','hidden');
   }
   else{
      $("#ski").removeAttr('hidden');
      var filter = $('#listing_industry').val();
      $(".skill_class option").show();
      $(".skill_class option[skill_ind]:not([skill_ind=\""+filter+"\"])").hide();
      $(".skill_class option[selected=selected])").select();
      $(".skill_class").val($('.skill_class option:visible:first').val());
   }

   $('#listing_industry').change(function(){
      if($(this).val() == ""){
        $("#ski").attr('hidden','hidden');
      }
      else{
        var filter = $('#listing_industry').val();
        $("#ski").removeAttr('hidden');
        $(".skill_class option").show();
        $(".skill_class option[skill_ind]:not([skill_ind=\""+filter+"\"])").hide();
        $(".skill_class").val($('.skill_class option:visible:first').val());
      }
   })
});
</script>
<head>
<div class="listing-form">
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Title:' %>
    <%= form.text_field :title, id: :listing_title %>
  </div>

  <div class="field">
    <%= form.label 'Industry:' %>
    <%= form.collection_select(:industry, Skill.select('distinct industry'), :industry, :industry, include_blank: true, :id =>'ind') %>
  </div>

  <div class="field">
    <%= form.label 'Location:' %>
    <%= form.text_field :location, id: :listing_location %>
  </div>

  <div class="field">
    <%= form.label :'Salary From:' %>
    <%= form.number_field :min_salary, id: :listing_min_salary %>
    <%= form.label :'To:', :class=> 'label_to' %>
    <%= form.number_field :max_salary, id: :listing_max_salary %>
  </div>

  <div class="field">
    <%= form.label 'Hours:' %>
    <%= form.select :hours, ['Full-Time','Part-Time','Casual','Contract']%>
  </div>

<div class="skills">
  <h2>Skills:</h2>
  <div class="field" id="ski">
    <%= form.select 'skill[][skill_id]', Skill.all.map {|s| [s.name, s.id, {:'skill_ind' => s.industry}]}, {:include_blank => true}, {:class => 'skill_class'} %><br />
    <%= form.select 'skill[][skill_id]', Skill.all.map {|s| [s.name, s.id, {:'skill_ind' => s.industry}]}, {:include_blank => true}, {:class => 'skill_class'} %><br /> 
    <%= form.select 'skill[][skill_id]', Skill.all.map {|s| [s.name, s.id, {:'skill_ind' => s.industry}]}, {:include_blank => true}, {:class => 'skill_class'} %><br />
    <%= form.select 'skill[][skill_id]', Skill.all.map {|s| [s.name, s.id, {:'skill_ind' => s.industry}]}, {:include_blank => true}, {:class => 'skill_class'} %><br />
    <%= form.select 'skill[][skill_id]', Skill.all.map {|s| [s.name, s.id, {:'skill_ind' => s.industry}]}, {:include_blank => true}, {:class => 'skill_class'} %><br />
  </div>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>
</div>

app/views/listings/_listing.html.erb
    <tbody>
        <tr>
            <td><%= listing.title %></td>
            <td><%= listing.id %></td>
        </tr>
    </tbody>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <% if @is_employer %>
      <th>Hours</th>
      <th>Title</th>
      <th>Location</th>
    <% else %>
      <th>ID</th>
      <th>Detail</th>
      <th>Edit</th>
      <th>Delete</th>
    <% end %>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
    <% if @is_employer %>
          <%# if warden.user.has_role? (:employer) %>
          <%= render 'dashlisting', listing: listing %>
        <tr>
        <% else %>
        <tr>
          <td>
          <%= warden.user.id %>
          </td>
       <% end %>
        <td><%= link_to 'Show', listing %></td>
        <td><% if @is_employer %><%= link_to 'Edit', edit_listing_path(listing) %><% else %>X<% end %></td>
        <td><% if @is_employer %><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %><% else %> X<% end %></td>
      </tr>
        <% if listing != @listings.last %>
          <td colspan=3></td>
          <% end %>
    <% end %>
  </tbody>
</table>

<br>

<div style= "text-align: center;"><%= link_to 'New Listing', new_listing_path %></div>
   

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<div class="listing">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @listings.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listings.body %>
</p>

<p>
  <strong>Min Salary:</strong>
  <%= @listings.min_salary %>
</p>

<p>
  <strong>Max Salary:</strong>
  <%= @listings.max_salary %>
</p>

<p>
  <strong>Location:</strong>
  <%= @listings.location %>
</p>
</div>
<% if @is_employer %>
<%= link_to 'Edit', edit_listing_path(@listing) %> |
<% end %>
<%= link_to 'Back', listings_path %>