config/routes.rb
Rails.application.routes.draw do
  # get 'hunter_profiles/new'
  root 'dashboards#index'

  resources :hunter_profiles do
    member do
      get 'offer'
      post 'offer'
    end
  end

  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations"
  }
  devise_scope :users do
    get 'sign_up', to: 'users/registrations#new'
    get 'sign_in', to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
  end

  # post 'offer', to: 'hunter_profiles#create_offer'

  resources :listings
  # resources :registrations
  # resources :sessions
  resources :hunter_profiles
  resources :employer_profiles

  # create new employments from the offer button
  resources :employments, only: [:new, :create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employment.rb
class Employment < ApplicationRecord
  belongs_to :listing
  belongs_to :hunter_profile

  # def offer(hunter)
  #   @employment = Employment.find(hunter_id: hunter.id)
  #   @employment.offer = true
  # end
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  before_action :set_employment, only: [:show, :edit, :update, :destroy]

  # GET /employments
  def index
    @employments = Employment.all
  end

  # GET /employments/1
  def show
  end

  # GET /employments/new
  def new
    @employment = Employment.new
  end

  # GET /employments/1/edit
  def edit
  end

  # POST /employments
  def create
    @employment = Employment.new(employment_params)

    if @employment.save
      redirect_to @employment, notice: 'Employment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /employments/1
  def update
    if @employment.update(employment_params)
      redirect_to @employment, notice: 'Employment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /employments/1
  def destroy
    @employment.destroy
    redirect_to employments_url, notice: 'Employment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employment
      @employment = Employment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def employment_params
      params.fetch(:employment, {})
    end
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/views/employments/_form.html.erb
<%= form_with(model: employment, local: true) do |form| %>
  <% if employment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employment.errors.count, "error") %> prohibited this employment from being saved:</h2>

      <ul>
      <% employment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employments/edit.html.erb
<h1>Editing Employment</h1>

<%= render 'form', employment: @employment %>

<%= link_to 'Show', @employment %> |
<%= link_to 'Home', root_path %>

app/views/employments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employments.each do |employment| %>
      <tr>
        <td><%= link_to 'Show', employment %></td>
        <td><%= link_to 'Destroy', employment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', root_path %>

app/views/employments/new.html.erb
<h1>New Employment</h1>

<%= render 'form', employment: @employment %>

<%= link_to 'Home', root_path %>

app/views/employments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_employment_path(@employment) %> |
<%= link_to 'Home', root_path %>