config/routes.rb
Rails.application.routes.draw do
  # get 'hunter_profiles/new'
  root 'dashboards#index'

  resources :hunter_profiles do
    member do
      get 'offer'
      post 'offer'
    end
  end

  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations"
  }
  devise_scope :users do
    get 'sign_up', to: 'users/registrations#new'
    get 'sign_in', to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
  end

  # post 'offer', to: 'hunter_profiles#create_offer'

  resources :listings
  # resources :registrations
  # resources :sessions
  resources :hunter_profiles
  resources :employer_profiles

  # create new employments from the offer button
  resources :employments, only: [:new, :create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/signup/_signupnav.html.erb
 <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar">
        <div class="container">
            <a href="/pages" class="navbar-brand text-warning">HireMe</a>            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" style="background-color: #304a74 !important;" id="navbarSupportedContent">
                <div class="navbar-nav mr-auto">
                    <span class="nav-item active"><a href="/pages" class="nav-link">Home</a></span>
                    <span class="nav-item"><a href="/jobs" class="nav-link">Browse</a></span>
                    <span class="nav-item"><a href="/pages/job-listings" class="nav-link">Job-Listings</a></span>
                    <span class="nav-item"><a href="/pages/aboutus" class="nav-link">About Us</a></span>
                    <span class="nav-item"><a href="/pages/return" class="nav-link">Return</a></span>
                </div>
                <div class="form-inline" style="list-style-type: none;">
                     <%= link_to "Log in", sign_in_path, class: "waves-effect waves-light btn btn-sm btn-info lighten-2" %>
                </div>
            </div>
        </div>
    </nav>
    <!--/.Navbar-->